unstable_features = true
edition = "2021"
version = "Two"

max_width = 100
group_imports = "StdExternalCrate"
match_block_trailing_comma = true
error_on_unformatted = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
