[package]
name = "mdfmt-js"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mdfmt_core = { path = "../mdfmt-core" }
serde-wasm-bindgen = "0.5"
wasm-bindgen = "0.2.87"
